In [1]:
import cv2
import numpy as np

In [49]:
K = np.array([[560,0,320],[0,560,240],[0,0,1]],dtype=np.float32)
rvec = np.array([0.1, 0.2, 0.3], np.float32)
R, _ = cv2.Rodrigues(rvec)
print(R)

[[ 0.93575478 -0.28316498  0.21019171]
 [ 0.30293274  0.9505806  -0.06803132]
 [-0.18054008  0.12733458  0.9752903 ]]


In [50]:
H = K @ R @ np.linalg.inv(K)

In [51]:
H /= H[2, 2]

In [52]:
print(H)

[[  8.13167334e-01  -2.05494329e-01   2.08879410e+02]
 [  2.20296830e-01   9.81705487e-01  -1.14703590e+02]
 [ -3.14872566e-04   2.22079034e-04   1.00000000e+00]]


In [53]:
H += np.random.randn(3,3)*0.0001

In [69]:
np.save('rotational_homography.npy', {'H': H, 'K': K})

In [70]:
data = np.load('../data/rotational_homography.npy').item()
H, K = data['H'], data['K']

In [71]:
H

array([[  8.13177705e-01,  -2.05605209e-01,   2.08879395e+02],
       [  2.20315456e-01,   9.81728315e-01,  -1.14703568e+02],
       [ -4.05734871e-04,   3.25349916e-04,   9.99951601e-01]], dtype=float32)

In [72]:
H_ = np.linalg.inv(K) @ H @ K

In [75]:
w, u, vt = cv2.SVDecomp(H_)
R = u @ vt
if cv2.determinant(R) < 0:
    R *= 1

In [76]:
rvec = cv2.Rodrigues(R)[0]

In [77]:
print('Rotation vector:')
print(rvec)

Rotation vector:
[[ 0.12439561]
 [ 0.22688715]
 [ 0.32641321]]
